### ISSUE TITLE
two json feeds

### ISSUE THREAD

**Issue by vonglahn** [amcolash/MMM-json-feed#8]
Hello,

I want to display two json feeds but the information are messed up. Some of the values are missing. What ca I do?

**Comment by amcolash** [comment]
Currently there is no support for multiple data sources. See [issue 5](https://github.com/amcolash/MMM-json-feed/issues/5) for one solution.

**Comment by vonglahn** [comment]
Hy there,

yes it's hackish and yes it works. Thank you.
I would be happy if this feature is added in the future.

**Comment by amcolash** [comment]
At this point, there are no plans to further this module. It was made as an example for my own needs. If you would like to make a PR with the modified code, feel free to!

**Comment by amcolash** [comment]
I actually had some extra time today and I wanted to add this feature in for real since it is easy to do and honestly only took a few minutes to do. It does not have support for the titles of the different sources (I think that should stay separate like mentioned in the above workaround). Additionally, it will start clobbering things if there are matching keys in different sources. Anyways, use as follows:

```
urls: [
        'http://your.server.json.here/abc1.json',
        'http://your.server.json.here/abc2.json',
      ]
```

That is it!
